services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL}
        STRAPI_URL: ${STRAPI_URL}
        NEXT_PUBLIC_MEDUSA_BACKEND_URL: ${NEXT_PUBLIC_MEDUSA_BACKEND_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
    networks:
      - booking-jewel_jewellery_network

networks:
  booking-jewel_jewellery_network:
    external: true