services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://strapi.navloka.in
        STRAPI_URL: https://strapi.navloka.in
        NEXT_PUBLIC_MEDUSA_BACKEND_URL: https://medusa.navloka.in
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: https://strapi.navloka.in
      STRAPI_URL: https://strapi.navloka.in
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: https://medusa.navloka.in
    restart: unless-stopped
    networks:
      - booking-jewel_jewellery_network

networks:
  booking-jewel_jewellery_network:
    external: true