import { Info, X } from "lucide-react";

export function PriceBreakupModal({ isOpen, onClose, product, selectedVariant }: { isOpen: boolean; onClose: () => void; product: any; selectedVariant: any }) {
    if (!isOpen) return null;
    const price = selectedVariant?.calculated_price ?? product.variants?.[0]?.calculated_price;
    const amount = price?.calculated_amount ?? 0;
    const original = price?.original_amount ?? amount;
    const currency = price?.currency_code ?? "inr";
    const format = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: currency.toUpperCase(), maximumFractionDigits: 0 }).format(value);
    return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/55 p-4"><div className="w-full max-w-lg rounded border border-border bg-background p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">Price details</p><h2 className="mt-2 font-heading text-3xl text-text-primary">{product.title}</h2></div><button onClick={onClose} className="rounded-full border border-border p-2"><X className="h-4 w-4" /></button></div><div className="mt-6 divide-y divide-border rounded border border-border bg-white"><div className="flex justify-between gap-4 p-4 text-sm"><span className="text-text-secondary">Variant</span><span className="text-right font-medium">{selectedVariant?.title || "Default variant"}</span></div>{original > amount && <div className="flex justify-between p-4 text-sm"><span className="text-text-secondary">Original price</span><span className="line-through">{format(original)}</span></div>}<div className="flex items-center justify-between bg-surface p-4"><span className="font-semibold">Current price</span><span className="font-heading text-2xl font-semibold">{amount ? format(amount) : "Unavailable"}</span></div></div><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-text-secondary"><Info className="mt-0.5 h-4 w-4 flex-none text-gold" />This is the calculated Medusa price. Detailed material and making-charge components require corresponding product metadata from the merchant.</p><button onClick={onClose} className="mt-6 w-full rounded bg-text-primary px-5 py-3 text-xs font-semibold uppercase tracking-wider text-white">Close</button></div></div>;
}
