import { Info, ShieldCheck } from "lucide-react";

export function PriceBreakdown({ product, selectedVariant }: { product: any; selectedVariant: any }) {
    const price = selectedVariant?.calculated_price ?? product.variants?.[0]?.calculated_price;
    const amount = price?.calculated_amount ?? 0;
    const original = price?.original_amount ?? amount;
    const currency = price?.currency_code ?? "inr";
    const format = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: currency.toUpperCase(), maximumFractionDigits: 0 }).format(value);
    return <section className="rounded border border-border bg-surface p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">Price details</p><h2 className="mt-2 font-heading text-2xl text-text-primary">Medusa calculated price</h2><div className="mt-5 divide-y divide-border rounded border border-border bg-white"><div className="flex items-center justify-between p-4 text-sm"><span className="text-text-secondary">Selected variant</span><span className="font-medium text-text-primary">{selectedVariant?.title || "Default variant"}</span></div>{original > amount && <div className="flex items-center justify-between p-4 text-sm"><span className="text-text-secondary">Original price</span><span className="text-text-secondary line-through">{format(original)}</span></div>}<div className="flex items-center justify-between bg-surface p-4"><span className="font-semibold text-text-primary">Current price</span><span className="font-heading text-2xl font-semibold text-text-primary">{amount ? format(amount) : "Unavailable"}</span></div></div><div className="mt-4 flex items-start gap-2 text-xs leading-5 text-text-secondary"><Info className="mt-0.5 h-4 w-4 flex-none text-gold" /><p>Metal value, making charges and tax are shown only when configured by the merchant; the checkout total is calculated by Medusa.</p></div><div className="mt-4 flex items-center gap-2 text-xs font-semibold text-emerald-800"><ShieldCheck className="h-4 w-4" />No frontend-generated price estimates</div></section>;
}
