"use client";

import { useState } from "react";
import { ChevronDown, Gem, Ruler, Sparkles } from "lucide-react";

export function ProductDetailsAccordion({ product, selectedVariant }: { product: any; selectedVariant: any; onOpenCertificateModal?: () => void; onOpenExchangeModal?: () => void }) {
    const [open, setOpen] = useState<Record<string, boolean>>({ details: true, dimensions: false, care: false });
    const metadata = product.metadata ?? {};
    const details = [["SKU", selectedVariant?.sku], ["Collection", product.collection?.title], ["Category", product.categories?.map((item: any) => item.name).join(", ")], ["Material", product.material || metadata.material], ["Purity", metadata.purity], ["Country of origin", product.origin_country]];
    const dimensions = [["Weight", product.weight && `${product.weight}${metadata.weight_unit || "g"}`], ["Length", product.length && `${product.length}${metadata.dimension_unit || "mm"}`], ["Width", product.width && `${product.width}${metadata.dimension_unit || "mm"}`], ["Height", product.height && `${product.height}${metadata.dimension_unit || "mm"}`]];
    return <div className="space-y-3"><Panel title="Product details" icon={<Sparkles />} open={open.details} toggle={() => setOpen({ ...open, details: !open.details })}><Rows rows={details} /><p className="mt-4 text-sm leading-6 text-text-secondary">{product.description || "Product information is managed in Medusa."}</p></Panel>{dimensions.some(([, value]) => value) && <Panel title="Weight and dimensions" icon={<Ruler />} open={open.dimensions} toggle={() => setOpen({ ...open, dimensions: !open.dimensions })}><Rows rows={dimensions} /></Panel>}<Panel title="Care information" icon={<Gem />} open={open.care} toggle={() => setOpen({ ...open, care: !open.care })}><p className="text-sm leading-6 text-text-secondary">{metadata.care_instructions || "Store separately in a soft pouch, keep away from chemicals and have the piece inspected periodically by a jewellery professional."}</p></Panel></div>;
}

function Panel({ title, icon, open, toggle, children }: { title: string; icon: React.ReactNode; open: boolean; toggle: () => void; children: React.ReactNode }) { return <section className="overflow-hidden rounded border border-border bg-background"><button onClick={toggle} className="flex w-full items-center justify-between px-5 py-4 text-left"><span className="flex items-center gap-2.5 text-sm font-semibold text-text-primary"><span className="text-gold [&>svg]:h-4 [&>svg]:w-4">{icon}</span>{title}</span><ChevronDown className={`h-4 w-4 text-text-secondary transition ${open ? "rotate-180" : ""}`} /></button>{open && <div className="border-t border-border px-5 py-5">{children}</div>}</section>; }
function Rows({ rows }: { rows: any[][] }) { const visible = rows.filter(([, value]) => value !== undefined && value !== null && value !== ""); return visible.length ? <dl className="grid gap-x-6 sm:grid-cols-2">{visible.map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-border py-2.5 text-xs"><dt className="text-text-secondary">{label}</dt><dd className="text-right font-medium text-text-primary">{String(value)}</dd></div>)}</dl> : <p className="text-sm text-text-secondary">Additional specifications have not been configured in Medusa.</p>; }
